[theme]
base="light"
primaryColor="#0057B7"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#FFFFFF"
textColor="#1E1E1E"
font="sans serif"

[client]
toolbarMode="hidden"

[browser]
gatherUsageStats = false
